package com.jojolaptech.camel.model.postgres.enums;

public enum CurrencyCode {

    AED("United Arab Emirates Dirham", "د.إ"),
    AFN("Afghan Afghani", "؋"),
    ALL("Albanian Lek", "L"),
    AMD("Armenian Dram", "֏"),
    ANG("Netherlands Antillean Guilder", "ƒ"),
    AOA("Angolan Kwanza", "Kz"),
    ARS("Argentine Peso", "$"),
    AUD("Australian Dollar", "$"),
    AWG("Aruban Florin", "ƒ"),
    AZN("Azerbaijani Manat", "₼"),
    BAM("Bosnia-Herzegovina Convertible Mark", "KM"),
    BBD("Barbadian Dollar", "$"),
    BDT("Bangladeshi Taka", "৳"),
    BGN("Bulgarian Lev", "лв"),
    BHD("Bahraini Dinar", ".د.ب"),
    BIF("Burundian Franc", "FBu"),
    BMD("Bermudian Dollar", "$"),
    BND("Brunei Dollar", "$"),
    BOB("Bolivian Boliviano", "Bs."),
    BRL("Brazilian Real", "R$"),
    BSD("Bahamian Dollar", "$"),
    BTN("Bhutanese Ngultrum", "Nu."),
    BWP("Botswana Pula", "P"),
    BYN("Belarusian Ruble", "Br"),
    BZD("Belize Dollar", "$"),
    CAD("Canadian Dollar", "$"),
    CDF("Congolese Franc", "FC"),
    CHF("Swiss Franc", "CHF"),
    CLP("Chilean Peso", "$"),
    CNY("Chinese Yuan", "¥"),
    COP("Colombian Peso", "$"),
    CRC("Costa Rican Colón", "₡"),
    CUP("Cuban Peso", "$"),
    CVE("Cape Verdean Escudo", "$"),
    CZK("Czech Koruna", "Kč"),
    DJF("Djiboutian Franc", "Fdj"),
    DKK("Danish Krone", "kr"),
    DOP("Dominican Peso", "RD$"),
    DZD("Algerian Dinar", "د.ج"),
    EGP("Egyptian Pound", "£"),
    ERN("Eritrean Nakfa", "Nfk"),
    ETB("Ethiopian Birr", "Br"),
    EUR("Euro", "€"),
    FJD("Fijian Dollar", "$"),
    FKP("Falkland Islands Pound", "£"),
    FOK("Faroese Króna", "kr"),
    GBP("British Pound Sterling", "£"),
    GEL("Georgian Lari", "₾"),
    GGP("Guernsey Pound", "£"),
    GHS("Ghanaian Cedi", "₵"),
    GIP("Gibraltar Pound", "£"),
    GMD("Gambian Dalasi", "D"),
    GNF("Guinean Franc", "FG"),
    GTQ("Guatemalan Quetzal", "Q"),
    GYD("Guyanese Dollar", "$"),
    HKD("Hong Kong Dollar", "$"),
    HNL("Honduran Lempira", "L"),
    HRK("Croatian Kuna", "kn"),
    HTG("Haitian Gourde", "G"),
    HUF("Hungarian Forint", "Ft"),
    IDR("Indonesian Rupiah", "Rp"),
    ILS("Israeli New Shekel", "₪"),
    IMP("Isle of Man Pound", "£"),
    INR("Indian Rupee", "₹"),
    IQD("Iraqi Dinar", "ع.د"),
    IRR("Iranian Rial", "﷼"),
    ISK("Icelandic Króna", "kr"),
    JEP("Jersey Pound", "£"),
    JMD("Jamaican Dollar", "$"),
    JOD("Jordanian Dinar", "د.ا"),
    JPY("Japanese Yen", "¥"),
    KES("Kenyan Shilling", "KSh"),
    KGS("Kyrgyzstani Som", "с"),
    KHR("Cambodian Riel", "៛"),
    KID("Kiribati Dollar", "$"),
    KMF("Comorian Franc", "CF"),
    KRW("South Korean Won", "₩"),
    KWD("Kuwaiti Dinar", "د.ك"),
    KYD("Cayman Islands Dollar", "$"),
    KZT("Kazakhstani Tenge", "₸"),
    LAK("Lao Kip", "₭"),
    LBP("Lebanese Pound", "ل.ل"),
    LKR("Sri Lankan Rupee", "Rs"),
    LRD("Liberian Dollar", "$"),
    LSL("Lesotho Loti", "L"),
    LYD("Libyan Dinar", "ل.د"),
    MAD("Moroccan Dirham", "د.م."),
    MDL("Moldovan Leu", "L"),
    MGA("Malagasy Ariary", "Ar"),
    MKD("Macedonian Denar", "ден"),
    MMK("Myanmar Kyat", "K"),
    MNT("Mongolian Tögrög", "₮"),
    MOP("Macanese Pataca", "MOP$"),
    MRU("Mauritanian Ouguiya", "UM"),
    MUR("Mauritian Rupee", "₨"),
    MVR("Maldivian Rufiyaa", "Rf"),
    MWK("Malawian Kwacha", "MK"),
    MXN("Mexican Peso", "$"),
    MYR("Malaysian Ringgit", "RM"),
    MZN("Mozambican Metical", "MT"),
    NAD("Namibian Dollar", "$"),
    NGN("Nigerian Naira", "₦"),
    NIO("Nicaraguan Córdoba", "C$"),
    NOK("Norwegian Krone", "kr"),
    NPR("Nepalese Rupee", "₨"),
    NZD("New Zealand Dollar", "$"),
    OMR("Omani Rial", "ر.ع."),
    PAB("Panamanian Balboa", "B/."),
    PEN("Peruvian Sol", "S/"),
    PGK("Papua New Guinean Kina", "K"),
    PHP("Philippine Peso", "₱"),
    PKR("Pakistani Rupee", "₨"),
    PLN("Polish Złoty", "zł"),
    PYG("Paraguayan Guaraní", "₲"),
    QAR("Qatari Riyal", "ر.ق"),
    RON("Romanian Leu", "lei"),
    RSD("Serbian Dinar", "дин."),
    RUB("Russian Ruble", "₽"),
    RWF("Rwandan Franc", "FRw"),
    SAR("Saudi Riyal", "ر.س"),
    SBD("Solomon Islands Dollar", "$"),
    SCR("Seychellois Rupee", "₨"),
    SDG("Sudanese Pound", "ج.س."),
    SEK("Swedish Krona", "kr"),
    SGD("Singapore Dollar", "$"),
    SHP("Saint Helena Pound", "£"),
    SLE("Sierra Leonean Leone", "Le"),
    SOS("Somali Shilling", "Sh"),
    SRD("Surinamese Dollar", "$"),
    SSP("South Sudanese Pound", "£"),
    STN("São Tomé and Príncipe Dobra", "Db"),
    SYP("Syrian Pound", "£"),
    SZL("Eswatini Lilangeni", "E"),
    THB("Thai Baht", "฿"),
    TJS("Tajikistani Somoni", "ЅМ"),
    TMT("Turkmenistani Manat", "m"),
    TND("Tunisian Dinar", "د.ت"),
    TOP("Tongan Paʻanga", "T$"),
    TRY("Turkish Lira", "₺"),
    TTD("Trinidad and Tobago Dollar", "TT$"),
    TVD("Tuvaluan Dollar", "$"),
    TWD("New Taiwan Dollar", "NT$"),
    TZS("Tanzanian Shilling", "TSh"),
    UAH("Ukrainian Hryvnia", "₴"),
    UGX("Ugandan Shilling", "USh"),
    USD("United States Dollar", "$"),
    UYU("Uruguayan Peso", "$U"),
    UZS("Uzbekistani Soʻm", "soʻm"),
    VES("Venezuelan Bolívar", "Bs."),
    VND("Vietnamese Dong", "₫"),
    VUV("Vanuatu Vatu", "VT"),
    WST("Samoan Tālā", "WS$"),
    XAF("Central African CFA Franc", "FCFA"),
    XCD("East Caribbean Dollar", "$"),
    XOF("West African CFA Franc", "CFA"),
    XPF("CFP Franc", "₣"),
    YER("Yemeni Rial", "﷼"),
    ZAR("South African Rand", "R"),
    ZMW("Zambian Kwacha", "ZK"),
    ZWL("Zimbabwean Dollar", "$");

    private final String fullName;
    private final String symbol;

    CurrencyCode(String fullName, String symbol) {
        this.fullName = fullName;
        this.symbol = symbol;
    }

    public String getFullName() {
        return fullName;
    }

    public String getSymbol() {
        return symbol;
    }
}
